query FindAllCharacters {
  characters {
    results {
      id
      name
      status
      species
      gender
      image
      episode {
        id
        name
        episode
      }
    }
  }
}
