query findUserAndPets {
  user {
    ...UserData
    pets {
      ...PetData
      owner {
        ...UserData
      }
    }
  }
}

fragment PetData on Pet {
  id
  createdAt
  name
  type
  img
}

fragment UserData on User {
  id
  username
}
