query FindShoesAndUser {
  me {
    ...UserData
    shoes {
      ...ShoeData
    }
  }
  shoes {
    ...ShoeData
    user {
      ...UserData
      shoes {
        ...ShoeData
      }
    }
  }
}

fragment UserData on User {
  email
  avatar
}

fragment ShoeData on Shoe {
  brand
  size
  ... on Sneaker {
    sport
  }
  ... on Boot {
    hasGrip
  }
}
